"""add token in db

Revision ID: 6eb7dd60e642
Revises: dfc7f5595173
Create Date: 2024-11-14 15:11:15.803440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eb7dd60e642'
down_revision: Union[str, None] = 'dfc7f5595173'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('nb_tokens_prompt', sa.Integer(), nullable=True))
    op.add_column('answers', sa.Column('nb_tokens_completion', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'nb_tokens_completion')
    op.drop_column('answers', 'nb_tokens_prompt')
    # ### end Alembic commands ###
