"""text explication

Revision ID: a5120a8daf9f
Revises: 5cc2750cfb90
Create Date: 2024-12-12 13:53:33.430927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5120a8daf9f'
down_revision: Union[str, None] = '5cc2750cfb90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('readme', sa.Text(), nullable=True))
    # ### end Alembic commands ###
    
     # Update existing rows to set the created_at field to the current timestamp
    op.execute(
        sa.text("UPDATE datasets SET readme = 'nr' WHERE readme IS NULL")
    )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasets', 'readme')
    # ### end Alembic commands ###
