"""ModeRaw schema for users given ouput

Revision ID: a8268f41cb83
Revises: 3473db3ff969
Create Date: 2025-02-21 19:19:34.639407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8268f41cb83'
down_revision: Union[str, None] = '3473db3ff969'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasets', 'has_output')
    op.add_column('models', sa.Column('has_raw_output', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'has_raw_output')
    op.add_column('datasets', sa.Column('has_output', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
