"""add created_at for answers

Revision ID: a8816ddd6dfd
Revises: 4c8e0b29de31
Create Date: 2024-12-06 13:48:40.277600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8816ddd6dfd'
down_revision: Union[str, None] = '4c8e0b29de31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###

     # Update existing rows to set the created_at field to the current timestamp
    op.execute(
        sa.text("UPDATE answers SET created_at = NOW() WHERE created_at IS NULL")
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'created_at')
    # ### end Alembic commands ###
