"""Table Initialization

Revision ID: dfc7f5595173
Revises: 
Create Date: 2024-11-09 03:34:21.634188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfc7f5595173'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('df', sa.JSON(), nullable=True),
    sa.Column('has_query', sa.Boolean(), nullable=True),
    sa.Column('has_output', sa.Boolean(), nullable=True),
    sa.Column('has_output_true', sa.Boolean(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('experiment_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('readme', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('prompt_system', sa.Text(), nullable=True),
    sa.Column('sampling_params', sa.JSON(), nullable=True),
    sa.Column('extra_params', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('readme', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('experiment_status', sa.String(), nullable=True),
    sa.Column('num_try', sa.Integer(), nullable=True),
    sa.Column('num_success', sa.Integer(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('experiment_set_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['experiment_set_id'], ['experiment_sets.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experiment_set_id', 'name', name='_expset_name_unique_constraint')
    )
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('num_line', sa.Integer(), nullable=True),
    sa.Column('error_msg', sa.String(), nullable=True),
    sa.Column('execution_time', sa.Integer(), nullable=True),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('metric_name', sa.String(), nullable=True),
    sa.Column('num_try', sa.Integer(), nullable=True),
    sa.Column('num_success', sa.Integer(), nullable=True),
    sa.Column('metric_status', sa.String(), nullable=True),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observation_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('observation', sa.JSON(), nullable=True),
    sa.Column('num_line', sa.Integer(), nullable=True),
    sa.Column('error_msg', sa.String(), nullable=True),
    sa.Column('execution_time', sa.Integer(), nullable=True),
    sa.Column('result_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observation_table')
    op.drop_table('results')
    op.drop_table('answers')
    op.drop_table('experiments')
    op.drop_table('models')
    op.drop_table('experiment_sets')
    op.drop_table('datasets')
    # ### end Alembic commands ###
