services:
  db:
    image: postgres:17
    container_name: postgres-albert-eg1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: eg1_dev
    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db:
    name: eg1_postgres_db
