"""add_emission_carbon_to_answers

Revision ID: 1305462f2e50
Revises: 4b903ee83b10
Create Date: 2025-04-17 17:39:59.788362

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1305462f2e50"
down_revision: Union[str, None] = "4b903ee83b10"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("answers", sa.Column("emission_carbon", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("answers", "emission_carbon")
    # ### end Alembic commands ###
