#!/bin/bash
# Environment Variable Management Script
# This script manages environment variables and secret injection

set -euo pipefail

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
ENVIRONMENT="${1:-staging}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Logging functions
log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check required environment variables
check_required_vars() {
    local required_vars=("SCW_ACCESS_KEY" "SCW_SECRET_KEY" "SCW_DEFAULT_PROJECT_ID")
    local missing_vars=()

    for var in "${required_vars[@]}"; do
        if [[ -z "${!var:-}" ]]; then
            missing_vars+=("$var")
        fi
    done

    if [[ ${#missing_vars[@]} -gt 0 ]]; then
        log_error "Missing required environment variables:"
        for var in "${missing_vars[@]}"; do
            echo "  - $var"
        done
        echo ""
        echo "Please set these variables and try again."
        echo "You can create a .env file in the project root with these variables."
        exit 1
    fi
}

# Load environment variables from .env file
load_env_file() {
    local env_file="$PROJECT_ROOT/.env"

    if [[ -f "$env_file" ]]; then
        log_info "Loading environment variables from $env_file"
        set -a
        source "$env_file"
        set +a
    else
        log_warn "No .env file found at $env_file"
        log_warn "Create one with your Scaleway credentials"
    fi
}

# Generate Terraform variables file
generate_tfvars() {
    local tfvars_file="$PROJECT_ROOT/infra/${ENVIRONMENT}/terraform.tfvars"

    log_info "Generating Terraform variables file: $tfvars_file"

    cat > "$tfvars_file" << EOF
# Generated by environment management script
# Do not edit manually - use ./scripts/manage-env.sh instead

environment = "$ENVIRONMENT"
project_id = "$SCW_DEFAULT_PROJECT_ID"
default_region = "$SCW_DEFAULT_REGION:-fr-par"
default_zone = "$SCW_DEFAULT_ZONE:-fr-par-2"

# Tags
extra_tags = {
  "ManagedBy" = "OpenTofu"
  "Environment" = "$ENVIRONMENT"
}
EOF

    log_info "Terraform variables file generated successfully"
}

# Validate environment
validate_environment() {
    log_info "Validating environment: $ENVIRONMENT"

    if [[ ! "$ENVIRONMENT" =~ ^(staging|production)$ ]]; then
        log_error "Invalid environment: $ENVIRONMENT"
        log_error "Must be 'staging' or 'production'"
        exit 1
    fi

    log_info "Environment validation passed"
}

# Main function
main() {
    log_info "Starting environment variable management for $ENVIRONMENT"

    # Load environment variables
    load_env_file

    # Check required variables
    check_required_vars

    # Validate environment
    validate_environment

    # Generate Terraform variables
    generate_tfvars

    log_info "Environment setup complete!"
    log_info "You can now run: tofu -chdir=infra/$ENVIRONMENT init"
}

# Show usage
usage() {
    echo "Usage: $0 <environment>"
    echo ""
    echo "Environments:"
    echo "  staging     - Setup staging environment"
    echo "  production  - Setup production environment"
    echo ""
    echo "Example:"
    echo "  $0 staging"
}

# Parse command line arguments
if [[ $# -eq 0 ]]; then
    usage
    exit 1
fi

case "${1:-}" in
    staging|production)
        main
        ;;
    -h|--help)
        usage
        exit 0
        ;;
    *)
        log_error "Unknown environment: $1"
        usage
        exit 1
        ;;
esac
