"""add_emission_carbon_in_observation

Revision ID: 0f62332b614f
Revises: 2da85821482a
Create Date: 2025-07-24 13:47:39.822154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f62332b614f'
down_revision: Union[str, None] = '2da85821482a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observation_table', sa.Column('emission_carbon', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('observation_table', 'emission_carbon')
    # ### end Alembic commands ###
