"""Locus extra df

Revision ID: 2affae2e4758
Revises: 4de07d9a67df
Create Date: 2025-01-21 11:26:21.456153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2affae2e4758'
down_revision: Union[str, None] = '4de07d9a67df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locustrun', sa.Column('custom_history_df', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locustrun', 'custom_history_df')
    # ### end Alembic commands ###
