"""support model thinking

Revision ID: 4b903ee83b10
Revises: d662c9622be1
Create Date: 2025-04-11 13:00:50.934462

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4b903ee83b10"
down_revision: Union[str, None] = "d662c9622be1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("answers", sa.Column("think", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("answers", "think")
    # ### end Alembic commands ###
