"""num_line unique contraints

Revision ID: 502a68292e65
Revises: 0d299020f16a
Create Date: 2024-12-15 22:42:34.637409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '502a68292e65'
down_revision: Union[str, None] = '0d299020f16a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_answer_num_line_unique_constraint', 'answers', ['num_line', 'experiment_id'])
    op.create_unique_constraint('_metric_num_line_unique_constraint', 'observation_table', ['num_line', 'result_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_metric_num_line_unique_constraint', 'observation_table', type_='unique')
    op.drop_constraint('_answer_num_line_unique_constraint', 'answers', type_='unique')
    # ### end Alembic commands ###
