"""model name alias

Revision ID: 50b99f91d8d8
Revises: 7e2ab5bde05b
Create Date: 2025-02-22 02:02:44.000077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50b99f91d8d8'
down_revision: Union[str, None] = '7e2ab5bde05b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('aliased_name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'aliased_name')
    # ### end Alembic commands ###
