"""answer tool call steps

Revision ID: 60178b942bcb
Revises: 50b99f91d8d8
Create Date: 2025-03-12 00:37:06.973891

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "60178b942bcb"
down_revision: Union[str, None] = "50b99f91d8d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("answers", sa.Column("tool_steps", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("answers", "tool_steps")
    # ### end Alembic commands ###
