"""add with_vision and prelude_prompt

Revision ID: 72c0779e25da
Revises: dcf62c3ab046
Create Date: 2025-05-03 17:41:20.599041

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "72c0779e25da"
down_revision: Union[str, None] = "dcf62c3ab046"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("experiments", sa.Column("with_vision", sa.Boolean(), nullable=True))
    op.add_column("models", sa.Column("prelude_prompt", sa.Text(), nullable=True))
    # ### end Alembic commands ###

    op.execute(sa.text("UPDATE experiments SET with_vision = FALSE WHERE with_vision IS NULL"))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("models", "prelude_prompt")
    op.drop_column("experiments", "with_vision")
    # ### end Alembic commands ###
