"""add optinal context in answer

Revision ID: d662c9622be1
Revises: fc07604306e5
Create Date: 2025-04-07 00:19:54.156243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd662c9622be1'
down_revision: Union[str, None] = 'fc07604306e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('context', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'context')
    # ### end Alembic commands ###
