"""add emission carbon

Revision ID: de6a4f1e935b
Revises: 10a7f6d91de4
Create Date: 2025-04-18 14:07:00.486850

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "de6a4f1e935b"
down_revision: Union[str, None] = "10a7f6d91de4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("answers", sa.Column("emission_carbon", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("answers", "emission_carbon")
    # ### end Alembic commands ###
