"""add retrieval_context

Revision ID: eee3dc59f461
Revises: 4c8e0b29de31
Create Date: 2024-11-29 13:38:11.359861

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eee3dc59f461"
down_revision: Union[str, None] = "4c8e0b29de31"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("answers", sa.Column("retrieval_context", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("answers", "retrieval_context")
    # ### end Alembic commands ###
