"""answer nb_tool_calls metric

Revision ID: fc07604306e5
Revises: 60178b942bcb
Create Date: 2025-04-04 17:54:39.514951

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fc07604306e5"
down_revision: Union[str, None] = "60178b942bcb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("answers", sa.Column("nb_tool_calls", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("answers", "nb_tool_calls")
    # ### end Alembic commands ###
