from typing import Any, Iterable, Protocol


class AutoCommitSession(Protocol):
    """Session contract for contexts that must not finalize transactions."""

    def add(self, instance: Any, _warn: bool = ...) -> None: ...

    def add_all(self, instances: Iterable[Any]) -> None: ...

    def delete(self, instance: Any) -> None: ...

    def execute(self, statement: Any, params: Any | None = ...) -> Any: ...

    def expire(self, instance: Any, attribute_names: list[str] | None = ...) -> None: ...

    def flush(self) -> None: ...

    def refresh(self, instance: Any, attribute_names: list[str] | None = ...) -> None: ...

    def query(self, *entities: Any, **kwargs: Any) -> Any: ...

    def scalar(self, statement: Any) -> Any: ...

    def close(self) -> None: ...


class AutoCloseSession(AutoCommitSession, Protocol):
    """Session contract for FastAPI request handlers that can safely commit/rollback."""

    def commit(self) -> None: ...

    def rollback(self) -> None: ...
